# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samuel Furlong
email: samfurlong1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Portfolio Site of Samuel Furlong, Developer | Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samuelfurlong.com" # the base hostname & protocol for your site
twitter_username: Sam_Furlong92
github_username:  samfurlong
linkedin_url:  "https://ie.linkedin.com/in/samfurlong"

# Build settings
markdown: kramdown

include: [
  '_projects',
  '_redirects'
]
exclude: [
  '_dev',
  'node_modules',
  'gulpfile.js',
  'package.json'
]

projects: [
  'ecalee',
  'saas-starter',
  'google-startup-weekend',
  'personal-portfolio',
  'prsuit',
  'cassin-marketing',
]
